apiVersion: v1
kind: Secret
metadata:
  name: secrets
data:
  db-url: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfN2pKUW1ZOGhCeWZFQGVwLXN0aWxsLW1vZGUtYWQxczc1eXguYy0yLnVzLWVhc3QtMS5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmUmY2hhbm5lbF9iaW5kaW5nPXJlcXVpcmU= # base64 encoded